/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/GuestCoupon': RouteRecordInfo<'/GuestCoupon', '/GuestCoupon', Record<never, never>, Record<never, never>>,
    '/GuestPersonal': RouteRecordInfo<'/GuestPersonal', '/GuestPersonal', Record<never, never>, Record<never, never>>,
    '/GuestVoucher': RouteRecordInfo<'/GuestVoucher', '/GuestVoucher', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/StaffScanner': RouteRecordInfo<'/StaffScanner', '/StaffScanner', Record<never, never>, Record<never, never>>,
  }
}
